idelic-inc/idelic-js

- packages/formatron-react/src/form/Form.tsx
This PR includes changes to `formatron-react` needed for https://github.com/idelic-inc/training-microfrontend/pull/3
> SAF-4674: Update "Confirmation" Wizard Step

- packages/safety-suite-api/src/config.ts
This PR fixes the config to match the changes that were made in this migration: https://github.com/idelic-inc/login/pull/245
> Update BasicConfig to match eforms changes.

- packages/safety-suite-api/src/api/integrations.ts
PR to support recent updates to https://github.com/idelic-inc/login/pull/242
> SAF-5020: Add labels to integrations

- packages/safety-suite-api/src/api/eForms.ts
Updated types based on [API reference update](https://github.com/idelic-inc/api-reference/pull/13) and [backend PR](https://github.com/idelic-inc/eforms-backend/pull/21).
> SAF-4988: Return data only for customer that admin currently looking at

- packages/safety-suite-api/src/api/eForms.ts
Added endpoint for getting driver user by employee id impelented in [SAF-4983](https://idelic.atlassian.net/browse/SAF-4983).
> Getting driver user by employee id

- packages/safety-suite-api/src/api/models/types.ts
Supports https://github.com/idelic-inc/safety-suite/pull/1881
> SAF-5013: Add ByCreatedBy OrderBy parameter.

- packages/safety-suite-api/src/api/models/index.ts
- packages/safety-suite-api/src/api/models/models.ts
- packages/safety-suite-api/src/legacyApi/models/models.ts
This PR adds support for an old route. `/api/models/bulk`
> SAF-5204: Add updateModels to safety-suite-api.

- packages/safety-suite-api/src/config.ts
This PR adds a watchlist enabled flag to the performanceDashboard in the config.
https://idelic.atlassian.net/browse/SAF-5444
> SAF-544: added watchlist to performance dashboard config

- packages/safety-suite-api/src/config.ts
https://idelic.atlassian.net/browse/SAF-5390
> SAF-5390: Use MFE CRA template to create new Admin Panel repo

- packages/safety-suite-api/src/config.ts
https://idelic.atlassian.net/browse/SAF-5456
> SAF-5456: added config flag for dashboard versions

- packages/safety-suite-api/src/api/models/queries.ts
- packages/safety-suite-api/src/api/models/types.ts
- packages/safety-suite-api/src/legacyApi/models/queries.ts
Required by [SAF-5358](https://idelic.atlassian.net/browse/SAF-5358).
Implemented in [SAF-5356](https://idelic.atlassian.net/browse/SAF-5356).
> Asynchronous model export API

- packages/formatron-react/package.json
- packages/formatron-react/yarn.lock
- packages/safety-suite-api/src/legacyApi/models/queries.ts
This PR added columnsTemplateId to ModelExport. This is for the expiring documents export.
> SAF-5502: Add export back to dashboard widgets.

- packages/safety-suite-api/src/legacyApi/monitors.ts
This PR adds query params to getMonitorModelsIdsParams.
https://idelic.atlassian.net/browse/SAF-5465
> SAF-5465:  Add readReplica query to monitor request FE.

- packages/safety-suite-api/src/api/models/queries.ts
Added endpoint for getting all non-expired export queries to show on initial app load.
> SAF-5483: get all export queries endpoint

- packages/safety-suite-api/src/api/models/__tests__/employee.test.ts
- packages/safety-suite-api/src/api/models/groups.ts
- packages/safety-suite-api/src/api/models/types.ts
- packages/safety-suite-api/src/legacyApi/admin.ts
- packages/safety-suite-api/src/legacyApi/enums.ts
- packages/safety-suite-api/src/legacyApi/models/documents.ts
- packages/safety-suite-api/src/legacyApi/notifications.ts
- packages/safety-suite-api/src/types.ts
https://idelic.atlassian.net/browse/SAF-5539
> SAF-5539: Replace user account identifier with user id across Safety Suite

- packages/safety-suite-api/src/config.ts
[SAF-5504](https://idelic.atlassian.net/browse/SAF-5504)
> SAF-5504: Remove the sisense iframe from safety-suite

- packages/safety-suite-api/src/api/configuration.ts
- packages/safety-suite-api/src/api/enums.ts
- packages/safety-suite-api/src/api/index.ts
- packages/safety-suite-api/src/api/listItems.ts
- packages/safety-suite-api/src/legacyApi/enums.ts
- packages/safety-suite-api/src/legacyApi/listItems.ts
Updated `listItems` and `enums` to the new API pattern with more accurate typings and documentation.
> SAF-5413: Compose the Roles Interface

- packages/safety-suite-api/src/api/dashboardSink/expirations.ts
This PR  updated the expiring docs endpoints and response.
> SAF-5671 3: updated expiring docs

- packages/safety-suite-api/src/api/dashboardSink/accidents.ts
- packages/safety-suite-api/src/api/dashboardSink/developmentPlans.ts
- packages/safety-suite-api/src/api/dashboardSink/enforcements.ts
- packages/safety-suite-api/src/api/dashboardSink/expirations.ts
- packages/safety-suite-api/src/api/dashboardSink/injuries.ts
- packages/safety-suite-api/src/api/dashboardSink/riskScores.ts
- packages/safety-suite-api/src/api/dashboardSink/types.ts
This PR fixed the preventable type on accidents and updated interface names to include dashboard.
> SAF-5671 4

- packages/safety-suite-api/src/config.ts
This PR added enabled flags for all dashboard widgets.
https://idelic.atlassian.net/browse/SAF-5606
> SAF-5606: Update PDP Widget to use Lincoln API endpoints

- packages/safety-suite-api/src/api/dashboardSink/riskScores.ts
- packages/safety-suite-api/src/api/dashboardSink/types.ts
This PR adds the riskScoreBucket query param to risk score table query.
https://idelic.atlassian.net/browse/SAF-5758
> SAF-5758: Update watch list widget to use lincoln endpoint risk score filter.

- packages/safety-suite-api/src/api/models/queries.ts
- packages/safety-suite-api/src/api/models/types.ts
- packages/safety-suite-api/src/legacyApi/models/queries.ts
Added endpoints implemented in [SAF-5578](https://idelic.atlassian.net/browse/SAF-5578), [SAF-5577](https://idelic.atlassian.net/browse/SAF-5577), [SAF-5576](https://idelic.atlassian.net/browse/SAF-5576), [SAF-5575](https://idelic.atlassian.net/browse/SAF-5575).
> Asynchronous Exports Endpoints

- packages/safety-suite-api/src/api/users.ts
This PR added getCurrentSafUser to safety-suite-api.
https://idelic.atlassian.net/browse/SAF-5804
> SAF-5717: Dashboard Hierarchy Filter Respects Current State Permissions

- packages/safety-suite-api/src/config.ts
This PR adds the hierarchy filter to the dashboard config.
> SAF-5804: Dashboard Hierarchy Filter Respects Current State Permissions

- packages/safety-suite-api/src/api/dashboardSink/accidents.ts
- packages/safety-suite-api/src/api/dashboardSink/developmentPlans.ts
- packages/safety-suite-api/src/api/dashboardSink/enforcements.ts
- packages/safety-suite-api/src/api/dashboardSink/expirations.ts
- packages/safety-suite-api/src/api/dashboardSink/injuries.ts
- packages/safety-suite-api/src/api/dashboardSink/types.ts
- packages/safety-suite-api/src/config.ts
https://idelic.atlassian.net/browse/SAF-5847
> SAF-5847: Clicking a driver name from the watch list widget takes you to an error page

- packages/safety-suite-api/src/api/dashboardSink/accidents.ts
- packages/safety-suite-api/src/api/dashboardSink/developmentPlans.ts
- packages/safety-suite-api/src/api/dashboardSink/enforcements.ts
- packages/safety-suite-api/src/api/dashboardSink/expirations.ts
- packages/safety-suite-api/src/api/dashboardSink/injuries.ts
- packages/safety-suite-api/src/api/dashboardSink/riskScores.ts
- packages/safety-suite-api/src/api/dashboardSink/types.ts
- packages/safety-suite-api/src/api/dashboardSink/util.ts
sort is no longer required
https://idelic.atlassian.net/browse/SAF-5845
> SAF-5845: The PDP table isn't populated on the new dashboard widgets

- packages/safety-suite-api/src/api/admin.ts
- packages/safety-suite-api/src/api/index.ts
Added endpoints implemented in
https://idelic.atlassian.net/browse/SAF-5425
https://idelic.atlassian.net/browse/SAF-5748
https://idelic.atlassian.net/browse/SAF-5747
> Business Hierarchy list, upload and download endpoints

- packages/safety-net/src/request.ts
- packages/safety-net/src/types.ts
https://idelic.atlassian.net/browse/SAF-5902
> SAF-5902: Driver Photos Error

- packages/safety-suite-api/src/api/userManagement/users.ts
https://idelic.atlassian.net/browse/SAF-5555
https://idelic.atlassian.net/browse/SAF-5556
> SAF-5555, SAF-5556: Deactivate, Reactivate

- packages/safety-suite-api/src/api/permission/roles.ts
https://idelic.atlassian.net/browse/SAF-5545
> SAF-5545: Superadmins and Admins can edit roles

- packages/safety-suite-api/src/config.ts
https://idelic.atlassian.net/browse/SAF-5938
> SAF-5938: Add config flags

- package.json
- packages/safety-suite-api/package.json
- packages/safety-suite-api/src/react/context/api.tsx
- packages/safety-suite-api/src/react/context/index.ts
- packages/safety-suite-api/src/react/hooks.ts
- packages/safety-suite-api/src/react/index.ts
- packages/safety-suite-api/tsconfig.json
- packages/safety-suite-api/yarn.lock
- yarn.lock
This PR adds context and hooks to safety-suite-api
> SAF-5987: Safety Suite API React Context and Hooks

- packages/safety-suite-api/src/api/admin.ts
- packages/safety-suite-api/src/api/permission/types.ts
- packages/safety-suite-api/src/index.ts
- packages/safety-suite-api/src/permissions.test.ts
- packages/safety-suite-api/src/permissions.ts
- packages/safety-suite-api/src/user.ts
https://idelic.atlassian.net/browse/SAF-6015
> SAF-6015: Create Permissions API class to support legacy and new permissions

- packages/safety-suite-api/src/api/dashboardSink/index.ts
- packages/safety-suite-api/src/api/dashboardSink/kpi.ts
- packages/safety-suite-api/src/api/dashboardSink/types.ts
> SAF-6070: Create Hub Enforcement KPI

- packages/safety-suite-api/src/api/admin.ts
https://idelic.atlassian.net/browse/SAF-5333
> SAF-5333:  Push Custom Dashboards through the UI

- packages/safety-suite-api/src/api/models/groups.ts
https://idelic.atlassian.net/browse/SAF-6282
> SAF-6282: Inactive terminals should not display in Dropdowns

- packages/safety-suite-api/src/api/dashboardSink/types.ts
This PR added a KpiNormalization interface to the KpiRequestBody interface.
https://idelic.atlassian.net/browse/SAF-6158
> SAF-6158: Normalize Data Request (FE)

- packages/safety-suite-api/src/api/dashboardSink/types.ts
This PR adds the rest of the kpi aggregations.
> update kpi aggregation

- packages/safety-suite-api/src/config.ts
To be merged after: https://github.com/idelic-inc/login/pull/373
> SAF-633, SAF-6384: License Status and Hub Goals config

- packages/safety-suite-api/src/api/userManagement/types.ts
- packages/safety-suite-api/src/types.ts
https://idelic.atlassian.net/browse/SAF-5827
> SAF:5827: Roles: Superadmins can view all users

- packages/safety-suite-api/src/api/dashboardSink/types.ts
This PR changed groups to groupings in the kpi request body.
https://idelic.atlassian.net/browse/SAF-6428
> SAF-6428: Rename datasets names to plural  (FE)

- packages/safety-suite-api/src/api/models/types.ts
- packages/safety-suite-api/src/legacyApi/models/models.ts
Change made as a result of [SAF-6286](https://idelic.atlassian.net/browse/SAF-6286
To be merged after https://github.com/idelic-inc/safety-suite/pull/2277
> Update Model Recompute to Restrict Computations

- packages/safety-suite-api/src/api/dashboardSink/types.ts
added normalization constant
https://idelic.atlassian.net/browse/SAF-6178
> SAF-6304: Create Hub Worklete KPI (FE)

- packages/safety-suite-api/src/config.ts
login config update: https://github.com/idelic-inc/login/pull/383
**note**: login need to be merged first
> SAF-6324: Add claims config typing

- packages/safety-suite-api/src/api/auditLog/index.ts
- packages/safety-suite-api/src/api/auditLog/log.ts
- packages/safety-suite-api/src/api/index.ts
- packages/safety-suite-api/src/config.ts
- packages/safety-suite-api/src/types.ts
https://idelic.atlassian.net/browse/SAF-5567
Based on https://idelic.atlassian.net/browse/SAF-6510
> SAF-5567: Audit log

- packages/safety-suite-api/src/config.ts
adding config flag for enforcementsTimeSeries
> SAF-6626: Time Series for Hub Enforcements (FE)

- package.json
- packages/formatron-react/package.json
- packages/formatron-react/yarn.lock
- packages/formatron/package.json
- packages/formatron/yarn.lock
- yarn.lock
Reverts idelic-inc/idelic-js#120
> Revert "SAF-6539: Update dependencies with security vulnerabilities"

- packages/safety-suite-api/src/config.ts
add lytxDriveCam to safety events dashboard config
https://idelic.atlassian.net/browse/SAF-6180
> SAF- 6180: Create Hub Lytx KPI (FE)

- packages/safety-suite-api/src/api/auditLog/log.ts
https://idelic.atlassian.net/browse/SAF-6743
> SAF-6743: Audit log type updates

- packages/safety-suite-api/src/config.ts
This PR added the discover tab feature flag to the config.
https://idelic.atlassian.net/browse/SAF-6721
> SAF-6721: New Feature Flag for Discover Dashboard (FE)

- packages/safety-suite-api/src/api/claims/claims.ts
https://idelic.atlassian.net/browse/SAF-6413?focusedCommentId=34944
> SAF-6413: Claims - Add Independent Claim from View/Add Claims (FE)

- packages/safety-suite-api/src/api/claims/balance.ts
> SAF-6990: Balance for claim type fix

- packages/safety-suite-api/src/api/claims/claims.ts
https://idelic.atlassian.net/browse/SAF-6915
> SAF-6915: Claims - Allow adding contacts while viewing/editing claims

- packages/safety-suite-api/src/config.ts
Add new feature flag `awards` to type.
Created the [PR](https://github.com/idelic-inc/login/pull/431) for `login` with adding a new feature flag as well.
> SAF-5450: Feature Flag for Awards

- packages/safety-suite-api/src/api/dashboardSink/types.ts
https://idelic.atlassian.net/browse/SAF-7209
> SAF-7209 - Add Most_recent_sum aggregation

- packages/safety-suite-api/src/api/claims/claims.ts
https://idelic.atlassian.net/browse/SAF-7229
> SAF-7229: Update Claim eventType field

- packages/safety-suite-api/src/api/models/types.ts
https://github.com/idelic-inc/safety-suite/blob/818eb313a14c5b7e2ae7a42460fa10b10e3d7486/backend/app/com/idelic/safetysuite/models/queries/ModelQueryService.scala#L51
> SAF-7083: RPH: Training & Development Manager role - trainings and PDPs

- packages/safety-suite-api/src/api/claims/claims.ts
- group id for delete claim (server arhitecture requirements)
- added description field for WorkersCompInfo
> SAF-7393: Add group id to delete claim

- packages/safety-suite-api/src/api/dashboardSink/types.ts
> SAF-7534: Update Metric Cards to include links to “Safety Suite Standard” charts (FE)

- packages/safety-suite-api/src/api/etl.ts
- packages/safety-suite-api/src/api/index.ts
- packages/safety-suite-api/src/config.ts
- packages/safety-suite-api/src/types.ts
[SAF-7532](https://idelic.atlassian.net/browse/SAF-7532)
> SAF-7532: Update Worklete query to support revised integration to Worklete Teams API

- packages/safety-suite-api/src/api/models/types.ts
https://idelic.atlassian.net/browse/SAF-7526
https://idelic.atlassian.net/browse/SAF-2420
> SAF-7526 - Specify field name (e.g 'terminal') for ByGroup sorting

- packages/safety-suite-api/src/api/dashboardSink/types.ts
https://idelic.atlassian.net/browse/SAF-7531
> SAF-7531: Define behavior for Relation Filters in Discover Dashboard

- packages/safety-suite-api/src/api/dashboardSink/types.ts
change bookmark interval to timePeriod
https://idelic.atlassian.net/browse/SAF-7697
> SAF-7697: Shared URL should pass 'Last 365 Days' instead of exact start and end dates (FE)

- packages/safety-suite-api/src/config.ts
https://idelic.atlassian.net/browse/SAF-7644
> SAF-7644: Update Kernel part to have feature flag for navigation with old PDP and new PDP

- packages/safety-suite-api/src/api/models/types.ts
- packages/safety-suite-api/src/api/permission/grants.ts
[SAF-7359](https://idelic.atlassian.net/browse/SAF-7359)
> SAF-7359: Add Export button to User Accounts page to export canned report

- packages/safety-suite-api/src/api/configService.ts
- packages/safety-suite-api/src/config.ts
[SAF-7473](https://idelic.atlassian.net/browse/SAF-7473)
> SAF-7473. List the configs for a given type

- packages/safety-suite-api/src/api/dashboardSink/types.ts
- packages/safety-suite-api/wiremock-stubs/dashboard-sink.json
change dashboardBookmarks to dashboardBookmarkList
https://idelic.atlassian.net/browse/SAF-8036
> SAF-8036: Saved bookmarks are not showing

- packages/safety-suite-api/src/api/claims/claims.ts
https://idelic.atlassian.net/browse/SAF-8004
> SAF-8004: Claims - add Incurred Loss column to Claims table (FE)

- packages/safety-suite-api/src/api/dashboardSink/bookmarks.ts
- packages/safety-suite-api/src/api/dashboardSink/types.ts
Updated the dashboard bookmark request functions to reflect the APIs defined here: https://api-reference.testing.idelic.software/service/dashboard-sink
> SAF-8042: Custom Bookmarks do not allow rearranging currently

- packages/safety-suite-api/src/api/claims/claims.ts
https://idelic.atlassian.net/browse/SAF-8020
> SAF-8020: Claims Event Type: remove forklift incident, bill of lading, material spill from dropdown (FE)

- packages/safety-suite-api/src/api/dashboardSink/types.ts
add filter priority weight
https://idelic.atlassian.net/browse/SAF-7972
> SAF-7972: Quick Filters Out of Order and Incorrect across data sets (FE)

- packages/safety-suite-api/src/api/claims/balance.ts
https://idelic.atlassian.net/browse/SAF-8108
> SAF-8108: new field added to balances

- packages/safety-suite-api/src/config.ts
Add new feature flag `notificationImprovements` to type.
Created the [PR](https://github.com/idelic-inc/login/pull/508) for login with adding a new feature flag as well.
> SAF-8119: Create config flag for Notification Improvements

- packages/safety-suite-api/src/api/claims/claims.ts
[SAF-6880](https://idelic.atlassian.net/browse/SAF-6880)
> SAF-6880: Remove "Illness" from Injury/Illness screen headings.

- packages/safety-suite-api/src/config.ts
add hub university goal to config
https://idelic.atlassian.net/browse/SAF-8280
> SAF-8280: Hub Group - MTD and YTD Completion Rate % for Hub University

- packages/safety-suite-api/src/api/models/modelTypes.ts
add description field to ImprovementPlanTaskFields
https://idelic.atlassian.net/browse/SAF-8626
[SAF-8626]: https://idelic.atlassian.net/browse/SAF-8626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SAF-8626: Move PDP Record Page to New MFE

- packages/safety-suite-api/src/api/models/modelTypes.ts
This PR removes the mileage and fuel models.
https://idelic.atlassian.net/browse/SAF-8765
> SAF-8765: Remove Mileage and Fuel Table From the Employee Templates

- packages/safety-suite-api/src/api/notifications/index.ts
- packages/safety-suite-api/src/api/notifications/subscriptions.ts
- packages/safety-suite-api/src/api/notifications/types.ts
- packages/safety-suite-api/src/config.ts
- packages/safety-suite-api/src/types.ts
add notification subscription endpoints
https://idelic.atlassian.net/browse/SAF-8581
https://idelic.atlassian.net/browse/SAF-8642
https://idelic.atlassian.net/browse/SAF-8643
https://idelic.atlassian.net/browse/SAF-8584
> SAF-8642: Hook "Upon Task Assignment" alert to the new notification service endpoints (FE)

- packages/safety-suite-api/src/api/claims/claims.ts
This PR adds the claim cost center.
https://idelic.atlassian.net/browse/SAF-8737
> SAF-8737: Add Claim Cost Center Field in Claims Module

- packages/safety-suite-api/src/api/dashboardSink/types.ts
The changes here reflect the work done as part of https://github.com/idelic-inc/dashboard-sink/pull/488
> SAF-9023: Normalize by Driver Count Columns

- packages/safety-suite-api/src/api/models/modelTypes.ts
https://idelic.atlassian.net/browse/SAF-9777
> SAF-9777: Adding Closed - Incomplete Status to PDP and Tasks
